const constants = {
    CREATE_TO_DO: 'CREATE_TO_DO',
    CREATE_TO_DO_SUCCESS: 'CREATE_TO_DO_SUCCESS',
    CREATE_TO_DO_ERROR: 'CREATE_TO_DO_ERROR',
    LIST_TO_DO:'LIST-TO_DO',
    LIST_TO_DO_SUCCESS:'LIST-TO_DO_SUCCESS',
    LIST_TO_DO_ERROR:'LIST-TO_DO_ERROR',
    TOGGLE_TO_DO:'TOGGLE_TO_DO',
    TOGGLE_TO_DO_SUCCESS:'TOGGLE_TO_DO_SUCCESS',
    TOGGLE_TO_DO_ERROR:'TOGGLE_TO_DO_ERROR',
    DELETE_TO_DO:'DELETE_TO_DO',
    DELETE_TO_DO_SUCCESS:'DELETE_TO_DO_SUCCESS',
    DELETE_TO_DO_ERROR:'DELETE_TO_DO_ERROR'
}
export default constants;