const constants = {
    CREATE_TO_DO: 'CREATE_TO_DO',
    CREATE_TO_DO_SUCCESS: 'CREATE_TO_DO_SUCCESS',
    CREATE_TO_DO_ERROR: 'CREATE_TO_DO_ERROR',
    REQUEST_LIST_TO_DO:'REQUEST_LIST-TO_DO',
    REQUEST_LIST_TO_DO_SUCCESS:'LIST-TO_DO_SUCCESS',
    REQUEST_LIST_TO_DO_ERROR:'LIST-TO_DO_ERROR',
    TOGGLE_TO_DO:'TOGGLE_TO_DO',
    TOGGLE_TO_DO_SUCCESS:'TOGGLE_TO_DO_SUCCESS',
    TOGGLE_TO_DO_ERROR:'TOGGLE_TO_DO_ERROR',
    DELETE_TO_DO:'DELETE_TO_DO',
    DELETE_TO_DO_SUCCESS:'DELETE_TO_DO_SUCCESS',
    DELETE_TO_DO_ERROR:'DELETE_TO_DO_ERROR',
    EDIT_TO_DO:'EDIT_TO_DO',
    EDIT_TO_DO_SUCCESS:'EDIT_TO_DO_SUCCESS',
    EDIT_TO_DO_ERROR:'EDIT_TO_DO_ERROR'
}
export default constants;